[2023-04-28 20:54:53,936] {processor.py:163} INFO - Started process (PID=178) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:54:53,937] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 20:54:53,937] {logging_mixin.py:109} INFO - [2023-04-28 20:54:53,937] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:54:53,966] {logging_mixin.py:109} INFO - [2023-04-28 20:54:53,963] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-04-28 20:54:53,978] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:54:53,985] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.052 seconds
[2023-04-28 20:55:24,116] {processor.py:163} INFO - Started process (PID=200) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:55:24,117] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 20:55:24,118] {logging_mixin.py:109} INFO - [2023-04-28 20:55:24,117] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:55:24,136] {logging_mixin.py:109} INFO - [2023-04-28 20:55:24,133] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-04-28 20:55:24,146] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:55:24,152] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.037 seconds
[2023-04-28 20:55:54,285] {processor.py:163} INFO - Started process (PID=222) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:55:54,286] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 20:55:54,287] {logging_mixin.py:109} INFO - [2023-04-28 20:55:54,287] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:55:54,306] {logging_mixin.py:109} INFO - [2023-04-28 20:55:54,304] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-04-28 20:55:54,318] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:55:54,324] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.040 seconds
[2023-04-28 20:56:24,469] {processor.py:163} INFO - Started process (PID=244) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:56:24,470] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 20:56:24,471] {logging_mixin.py:109} INFO - [2023-04-28 20:56:24,471] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:56:24,491] {logging_mixin.py:109} INFO - [2023-04-28 20:56:24,488] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-04-28 20:56:24,504] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:56:24,511] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.043 seconds
[2023-04-28 20:56:34,572] {processor.py:163} INFO - Started process (PID=266) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:56:34,573] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 20:56:34,574] {logging_mixin.py:109} INFO - [2023-04-28 20:56:34,574] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:56:34,955] {logging_mixin.py:109} INFO - [2023-04-28 20:56:34,951] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 43, in <module>
    python_callable=ingest_callable,
NameError: name 'ingest_callable' is not defined
[2023-04-28 20:56:34,966] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:56:34,972] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.401 seconds
[2023-04-28 20:57:05,097] {processor.py:163} INFO - Started process (PID=300) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:57:05,098] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 20:57:05,099] {logging_mixin.py:109} INFO - [2023-04-28 20:57:05,099] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:57:05,489] {logging_mixin.py:109} INFO - [2023-04-28 20:57:05,486] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import main
ImportError: cannot import name 'main' from 'load_data' (/opt/airflow/dags/load_data.py)
[2023-04-28 20:57:05,501] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:57:05,506] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.411 seconds
[2023-04-28 20:57:14,363] {processor.py:163} INFO - Started process (PID=317) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:57:14,364] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 20:57:14,365] {logging_mixin.py:109} INFO - [2023-04-28 20:57:14,365] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:57:14,752] {logging_mixin.py:109} INFO - [2023-04-28 20:57:14,749] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 43, in <module>
    python_callable=ingest_callable,
NameError: name 'ingest_callable' is not defined
[2023-04-28 20:57:14,763] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:57:14,769] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.408 seconds
[2023-04-28 20:57:18,582] {processor.py:163} INFO - Started process (PID=334) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:57:18,583] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 20:57:18,583] {logging_mixin.py:109} INFO - [2023-04-28 20:57:18,583] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:57:18,959] {processor.py:654} INFO - DAG(s) dict_keys(['LocalIngestionDag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:57:19,886] {logging_mixin.py:109} INFO - [2023-04-28 20:57:19,886] {manager.py:496} INFO - Created Permission View: can edit on DAG:LocalIngestionDag
[2023-04-28 20:57:19,892] {logging_mixin.py:109} INFO - [2023-04-28 20:57:19,892] {manager.py:496} INFO - Created Permission View: can read on DAG:LocalIngestionDag
[2023-04-28 20:57:19,892] {logging_mixin.py:109} INFO - [2023-04-28 20:57:19,892] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 20:57:19,897] {logging_mixin.py:109} INFO - [2023-04-28 20:57:19,897] {dag.py:2415} INFO - Creating ORM DAG for LocalIngestionDag
[2023-04-28 20:57:19,904] {logging_mixin.py:109} INFO - [2023-04-28 20:57:19,904] {dag.py:2935} INFO - Setting next_dagrun for LocalIngestionDag to 2021-01-02 06:00:00+00:00
[2023-04-28 20:57:19,913] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 1.333 seconds
[2023-04-28 20:57:32,483] {processor.py:163} INFO - Started process (PID=368) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:57:32,484] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 20:57:32,484] {logging_mixin.py:109} INFO - [2023-04-28 20:57:32,484] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:57:32,512] {logging_mixin.py:109} INFO - [2023-04-28 20:57:32,509] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-04-28 20:57:32,524] {processor.py:690} INFO - Deactivated 1 DAGs which are no longer present in /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:57:32,525] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:57:32,531] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.050 seconds
[2023-04-28 20:57:38,517] {processor.py:163} INFO - Started process (PID=373) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:57:38,518] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 20:57:38,519] {logging_mixin.py:109} INFO - [2023-04-28 20:57:38,519] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:57:38,549] {logging_mixin.py:109} INFO - [2023-04-28 20:57:38,545] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-04-28 20:57:38,562] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:57:38,571] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.056 seconds
[2023-04-28 20:58:08,704] {processor.py:163} INFO - Started process (PID=395) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:58:08,705] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 20:58:08,705] {logging_mixin.py:109} INFO - [2023-04-28 20:58:08,705] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:58:08,722] {logging_mixin.py:109} INFO - [2023-04-28 20:58:08,719] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-04-28 20:58:08,731] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:58:08,737] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.035 seconds
[2023-04-28 20:58:38,864] {processor.py:163} INFO - Started process (PID=417) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:58:38,865] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 20:58:38,865] {logging_mixin.py:109} INFO - [2023-04-28 20:58:38,865] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:58:38,881] {logging_mixin.py:109} INFO - [2023-04-28 20:58:38,879] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-04-28 20:58:38,891] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:58:38,897] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.034 seconds
[2023-04-28 20:59:09,026] {processor.py:163} INFO - Started process (PID=439) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:59:09,027] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 20:59:09,027] {logging_mixin.py:109} INFO - [2023-04-28 20:59:09,027] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:59:09,045] {logging_mixin.py:109} INFO - [2023-04-28 20:59:09,042] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-04-28 20:59:09,056] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:59:09,061] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.037 seconds
[2023-04-28 20:59:39,198] {processor.py:163} INFO - Started process (PID=461) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:59:39,199] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 20:59:39,199] {logging_mixin.py:109} INFO - [2023-04-28 20:59:39,199] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:59:39,583] {logging_mixin.py:109} INFO - [2023-04-28 20:59:39,580] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 43, in <module>
    python_callable=ingest_callable,
NameError: name 'ingest_callable' is not defined
[2023-04-28 20:59:39,594] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:59:39,600] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.403 seconds
[2023-04-28 20:59:42,639] {processor.py:163} INFO - Started process (PID=478) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:59:42,641] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 20:59:42,641] {logging_mixin.py:109} INFO - [2023-04-28 20:59:42,641] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:59:43,035] {processor.py:654} INFO - DAG(s) dict_keys(['LocalIngestionDag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 20:59:43,042] {logging_mixin.py:109} INFO - [2023-04-28 20:59:43,042] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 20:59:43,052] {logging_mixin.py:109} INFO - [2023-04-28 20:59:43,051] {dag.py:2935} INFO - Setting next_dagrun for LocalIngestionDag to 2021-01-02 06:00:00+00:00
[2023-04-28 20:59:43,063] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.426 seconds
[2023-04-28 21:00:05,209] {processor.py:163} INFO - Started process (PID=512) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:00:05,210] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:00:05,211] {logging_mixin.py:109} INFO - [2023-04-28 21:00:05,211] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:00:05,615] {processor.py:654} INFO - DAG(s) dict_keys(['LocalIngestionDag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:00:05,746] {logging_mixin.py:109} INFO - [2023-04-28 21:00:05,746] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:00:05,760] {logging_mixin.py:109} INFO - [2023-04-28 21:00:05,760] {dag.py:2935} INFO - Setting next_dagrun for LocalIngestionDag to 2021-01-02 06:00:00+00:00
[2023-04-28 21:00:05,770] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.563 seconds
[2023-04-28 21:00:35,919] {processor.py:163} INFO - Started process (PID=546) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:00:35,920] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:00:35,920] {logging_mixin.py:109} INFO - [2023-04-28 21:00:35,920] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:00:36,305] {processor.py:654} INFO - DAG(s) dict_keys(['LocalIngestionDag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:00:36,312] {logging_mixin.py:109} INFO - [2023-04-28 21:00:36,312] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:00:36,322] {logging_mixin.py:109} INFO - [2023-04-28 21:00:36,322] {dag.py:2935} INFO - Setting next_dagrun for LocalIngestionDag to 2021-01-02 06:00:00+00:00
[2023-04-28 21:00:36,330] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.413 seconds
[2023-04-28 21:01:06,471] {processor.py:163} INFO - Started process (PID=580) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:01:06,472] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:01:06,472] {logging_mixin.py:109} INFO - [2023-04-28 21:01:06,472] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:01:06,834] {processor.py:654} INFO - DAG(s) dict_keys(['LocalIngestionDag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:01:06,840] {logging_mixin.py:109} INFO - [2023-04-28 21:01:06,840] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:01:06,851] {logging_mixin.py:109} INFO - [2023-04-28 21:01:06,851] {dag.py:2935} INFO - Setting next_dagrun for LocalIngestionDag to 2021-01-02 06:00:00+00:00
[2023-04-28 21:01:06,858] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.389 seconds
[2023-04-28 21:01:36,989] {processor.py:163} INFO - Started process (PID=614) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:01:36,990] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:01:36,990] {logging_mixin.py:109} INFO - [2023-04-28 21:01:36,990] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:01:37,335] {processor.py:654} INFO - DAG(s) dict_keys(['LocalIngestionDag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:01:37,340] {logging_mixin.py:109} INFO - [2023-04-28 21:01:37,340] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:01:37,351] {logging_mixin.py:109} INFO - [2023-04-28 21:01:37,351] {dag.py:2935} INFO - Setting next_dagrun for LocalIngestionDag to 2021-01-02 06:00:00+00:00
[2023-04-28 21:01:37,358] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.370 seconds
[2023-04-28 21:02:07,502] {processor.py:163} INFO - Started process (PID=648) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:02:07,503] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:02:07,503] {logging_mixin.py:109} INFO - [2023-04-28 21:02:07,503] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:02:07,522] {logging_mixin.py:109} INFO - [2023-04-28 21:02:07,520] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:02:07,533] {processor.py:690} INFO - Deactivated 1 DAGs which are no longer present in /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:02:07,534] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:02:07,540] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.039 seconds
[2023-04-28 21:02:37,665] {processor.py:163} INFO - Started process (PID=670) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:02:37,666] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:02:37,667] {logging_mixin.py:109} INFO - [2023-04-28 21:02:37,667] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:02:37,692] {logging_mixin.py:109} INFO - [2023-04-28 21:02:37,689] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:02:37,706] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:02:37,714] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.050 seconds
[2023-04-28 21:03:07,833] {processor.py:163} INFO - Started process (PID=692) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:03:07,833] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:03:07,834] {logging_mixin.py:109} INFO - [2023-04-28 21:03:07,834] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:03:07,851] {logging_mixin.py:109} INFO - [2023-04-28 21:03:07,848] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:03:07,861] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:03:07,866] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.035 seconds
[2023-04-28 21:03:37,978] {processor.py:163} INFO - Started process (PID=714) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:03:37,978] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:03:37,979] {logging_mixin.py:109} INFO - [2023-04-28 21:03:37,979] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:03:37,998] {logging_mixin.py:109} INFO - [2023-04-28 21:03:37,995] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:03:38,009] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:03:38,016] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.039 seconds
[2023-04-28 21:03:40,997] {processor.py:163} INFO - Started process (PID=719) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:03:40,998] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:03:40,999] {logging_mixin.py:109} INFO - [2023-04-28 21:03:40,999] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:03:41,025] {logging_mixin.py:109} INFO - [2023-04-28 21:03:41,022] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:03:41,037] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:03:41,044] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.049 seconds
[2023-04-28 21:04:11,165] {processor.py:163} INFO - Started process (PID=741) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:04:11,165] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:04:11,166] {logging_mixin.py:109} INFO - [2023-04-28 21:04:11,166] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:04:11,182] {logging_mixin.py:109} INFO - [2023-04-28 21:04:11,180] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:04:11,193] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:04:11,198] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.035 seconds
[2023-04-28 21:04:41,368] {processor.py:163} INFO - Started process (PID=763) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:04:41,377] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:04:41,382] {logging_mixin.py:109} INFO - [2023-04-28 21:04:41,382] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:04:41,440] {logging_mixin.py:109} INFO - [2023-04-28 21:04:41,434] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:04:41,458] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:04:41,474] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.108 seconds
[2023-04-28 21:05:11,038] {processor.py:163} INFO - Started process (PID=785) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:05:11,039] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:05:11,040] {logging_mixin.py:109} INFO - [2023-04-28 21:05:11,040] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:05:11,070] {logging_mixin.py:109} INFO - [2023-04-28 21:05:11,066] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:05:11,083] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:05:11,090] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.053 seconds
[2023-04-28 21:05:27,155] {processor.py:163} INFO - Started process (PID=807) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:05:27,156] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:05:27,157] {logging_mixin.py:109} INFO - [2023-04-28 21:05:27,157] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:05:27,171] {logging_mixin.py:109} INFO - [2023-04-28 21:05:27,170] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 38
    bash_command=f'curl -sSL {URL_TEMPLATE} > {TAXI_OUTPUT_FILE_TEMPLATE = AIRFLOW_HOME + '/output_taxi_{{ execution_date.strftime(\'%Y-%m\') }}.csv'
                                                                                                        ^
SyntaxError: invalid syntax
[2023-04-28 21:05:27,181] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:05:27,187] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.033 seconds
[2023-04-28 21:05:35,198] {processor.py:163} INFO - Started process (PID=812) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:05:35,199] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:05:35,200] {logging_mixin.py:109} INFO - [2023-04-28 21:05:35,200] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:05:35,231] {logging_mixin.py:109} INFO - [2023-04-28 21:05:35,228] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:05:35,243] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:05:35,250] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.053 seconds
[2023-04-28 21:06:05,359] {processor.py:163} INFO - Started process (PID=834) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:06:05,360] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:06:05,360] {logging_mixin.py:109} INFO - [2023-04-28 21:06:05,360] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:06:05,377] {logging_mixin.py:109} INFO - [2023-04-28 21:06:05,375] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:06:05,387] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:06:05,393] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.036 seconds
[2023-04-28 21:06:35,501] {processor.py:163} INFO - Started process (PID=856) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:06:35,502] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:06:35,502] {logging_mixin.py:109} INFO - [2023-04-28 21:06:35,502] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:06:35,521] {logging_mixin.py:109} INFO - [2023-04-28 21:06:35,518] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:06:35,532] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:06:35,538] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.038 seconds
[2023-04-28 21:06:50,565] {processor.py:163} INFO - Started process (PID=861) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:06:50,565] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:06:50,566] {logging_mixin.py:109} INFO - [2023-04-28 21:06:50,566] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:06:50,598] {logging_mixin.py:109} INFO - [2023-04-28 21:06:50,594] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:06:50,612] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:06:50,621] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.058 seconds
[2023-04-28 21:07:20,750] {processor.py:163} INFO - Started process (PID=883) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:07:20,751] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:07:20,752] {logging_mixin.py:109} INFO - [2023-04-28 21:07:20,752] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:07:20,771] {logging_mixin.py:109} INFO - [2023-04-28 21:07:20,769] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:07:20,784] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:07:20,790] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.042 seconds
[2023-04-28 21:07:34,425] {processor.py:163} INFO - Started process (PID=905) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:07:34,426] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:07:34,426] {logging_mixin.py:109} INFO - [2023-04-28 21:07:34,426] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:07:34,454] {logging_mixin.py:109} INFO - [2023-04-28 21:07:34,451] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:07:34,466] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:07:34,472] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.049 seconds
[2023-04-28 21:08:04,586] {processor.py:163} INFO - Started process (PID=927) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:08:04,587] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:08:04,587] {logging_mixin.py:109} INFO - [2023-04-28 21:08:04,587] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:08:04,606] {logging_mixin.py:109} INFO - [2023-04-28 21:08:04,604] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:08:04,617] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:08:04,623] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.038 seconds
[2023-04-28 21:08:16,642] {processor.py:163} INFO - Started process (PID=932) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:08:16,642] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:08:16,643] {logging_mixin.py:109} INFO - [2023-04-28 21:08:16,643] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:08:16,676] {logging_mixin.py:109} INFO - [2023-04-28 21:08:16,672] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:08:16,689] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:08:16,696] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.056 seconds
[2023-04-28 21:08:30,743] {processor.py:163} INFO - Started process (PID=937) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:08:30,744] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:08:30,746] {logging_mixin.py:109} INFO - [2023-04-28 21:08:30,745] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:08:30,877] {logging_mixin.py:109} INFO - [2023-04-28 21:08:30,872] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:08:30,905] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:08:30,925] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.185 seconds
[2023-04-28 21:08:59,076] {processor.py:163} INFO - Started process (PID=959) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:08:59,076] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:08:59,077] {logging_mixin.py:109} INFO - [2023-04-28 21:08:59,077] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:08:59,107] {logging_mixin.py:109} INFO - [2023-04-28 21:08:59,104] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:08:59,118] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:08:59,125] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.051 seconds
[2023-04-28 21:09:04,703] {processor.py:163} INFO - Started process (PID=981) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:09:04,704] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:09:04,704] {logging_mixin.py:109} INFO - [2023-04-28 21:09:04,704] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:09:04,731] {logging_mixin.py:109} INFO - [2023-04-28 21:09:04,728] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:09:04,743] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:09:04,751] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.049 seconds
[2023-04-28 21:09:32,817] {processor.py:163} INFO - Started process (PID=986) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:09:32,817] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:09:32,818] {logging_mixin.py:109} INFO - [2023-04-28 21:09:32,818] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:09:32,846] {logging_mixin.py:109} INFO - [2023-04-28 21:09:32,843] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:09:32,858] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:09:32,866] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.051 seconds
[2023-04-28 21:09:37,459] {processor.py:163} INFO - Started process (PID=1008) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:09:37,460] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:09:37,460] {logging_mixin.py:109} INFO - [2023-04-28 21:09:37,460] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:09:37,486] {logging_mixin.py:109} INFO - [2023-04-28 21:09:37,483] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:09:37,497] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:09:37,502] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.045 seconds
[2023-04-28 21:10:07,626] {processor.py:163} INFO - Started process (PID=1030) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:10:07,626] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:10:07,627] {logging_mixin.py:109} INFO - [2023-04-28 21:10:07,627] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:10:07,643] {logging_mixin.py:109} INFO - [2023-04-28 21:10:07,641] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:10:07,654] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:10:07,659] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.035 seconds
[2023-04-28 21:10:37,765] {processor.py:163} INFO - Started process (PID=1052) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:10:37,766] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:10:37,767] {logging_mixin.py:109} INFO - [2023-04-28 21:10:37,767] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:10:37,789] {logging_mixin.py:109} INFO - [2023-04-28 21:10:37,786] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:10:37,799] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:10:37,806] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.042 seconds
[2023-04-28 21:11:07,911] {processor.py:163} INFO - Started process (PID=1074) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:11:07,912] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:11:07,912] {logging_mixin.py:109} INFO - [2023-04-28 21:11:07,912] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:11:07,931] {logging_mixin.py:109} INFO - [2023-04-28 21:11:07,928] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:11:07,942] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:11:07,950] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.040 seconds
[2023-04-28 21:11:38,038] {processor.py:163} INFO - Started process (PID=1079) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:11:38,039] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:11:38,039] {logging_mixin.py:109} INFO - [2023-04-28 21:11:38,039] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:11:38,060] {logging_mixin.py:109} INFO - [2023-04-28 21:11:38,057] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:11:38,071] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:11:38,078] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.042 seconds
[2023-04-28 21:12:08,208] {processor.py:163} INFO - Started process (PID=1101) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:12:08,209] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:12:08,210] {logging_mixin.py:109} INFO - [2023-04-28 21:12:08,210] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:12:08,229] {logging_mixin.py:109} INFO - [2023-04-28 21:12:08,227] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:12:08,240] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:12:08,246] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.039 seconds
[2023-04-28 21:12:38,379] {processor.py:163} INFO - Started process (PID=1123) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:12:38,379] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:12:38,380] {logging_mixin.py:109} INFO - [2023-04-28 21:12:38,380] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:12:38,398] {logging_mixin.py:109} INFO - [2023-04-28 21:12:38,395] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:12:38,408] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:12:38,413] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.036 seconds
[2023-04-28 21:13:08,551] {processor.py:163} INFO - Started process (PID=1145) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:13:08,552] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:13:08,553] {logging_mixin.py:109} INFO - [2023-04-28 21:13:08,552] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:13:08,571] {logging_mixin.py:109} INFO - [2023-04-28 21:13:08,569] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:13:08,582] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:13:08,588] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.039 seconds
[2023-04-28 21:13:38,720] {processor.py:163} INFO - Started process (PID=1167) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:13:38,721] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:13:38,721] {logging_mixin.py:109} INFO - [2023-04-28 21:13:38,721] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:13:38,738] {logging_mixin.py:109} INFO - [2023-04-28 21:13:38,736] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:13:38,748] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:13:38,753] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.035 seconds
[2023-04-28 21:14:08,881] {processor.py:163} INFO - Started process (PID=1189) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:14:08,882] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:14:08,882] {logging_mixin.py:109} INFO - [2023-04-28 21:14:08,882] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:14:08,900] {logging_mixin.py:109} INFO - [2023-04-28 21:14:08,898] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:14:08,910] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:14:08,916] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.036 seconds
[2023-04-28 21:14:36,832] {processor.py:163} INFO - Started process (PID=177) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:14:36,833] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:14:36,834] {logging_mixin.py:109} INFO - [2023-04-28 21:14:36,834] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:14:36,855] {logging_mixin.py:109} INFO - [2023-04-28 21:14:36,852] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 10, in <module>
    from load_data import load_data
ModuleNotFoundError: No module named 'load_data'
[2023-04-28 21:14:36,869] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:14:36,877] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.051 seconds
[2023-04-28 21:14:58,544] {processor.py:163} INFO - Started process (PID=199) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:14:58,545] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:14:58,545] {logging_mixin.py:109} INFO - [2023-04-28 21:14:58,545] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:14:59,024] {processor.py:654} INFO - DAG(s) dict_keys(['LocalIngestionDag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:14:59,162] {logging_mixin.py:109} INFO - [2023-04-28 21:14:59,162] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:14:59,174] {logging_mixin.py:109} INFO - [2023-04-28 21:14:59,174] {dag.py:2935} INFO - Setting next_dagrun for LocalIngestionDag to 2021-01-02 06:00:00+00:00
[2023-04-28 21:14:59,189] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.647 seconds
[2023-04-28 21:15:27,911] {processor.py:163} INFO - Started process (PID=177) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:15:27,912] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:15:27,913] {logging_mixin.py:109} INFO - [2023-04-28 21:15:27,913] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:15:28,383] {processor.py:654} INFO - DAG(s) dict_keys(['LocalIngestionDag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:15:28,388] {logging_mixin.py:109} INFO - [2023-04-28 21:15:28,387] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:15:28,401] {logging_mixin.py:109} INFO - [2023-04-28 21:15:28,401] {dag.py:2935} INFO - Setting next_dagrun for LocalIngestionDag to 2021-01-02 06:00:00+00:00
[2023-04-28 21:15:28,412] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.502 seconds
[2023-04-28 21:15:58,559] {processor.py:163} INFO - Started process (PID=211) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:15:58,560] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:15:58,560] {logging_mixin.py:109} INFO - [2023-04-28 21:15:58,560] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:15:58,982] {processor.py:654} INFO - DAG(s) dict_keys(['LocalIngestionDag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:15:58,990] {logging_mixin.py:109} INFO - [2023-04-28 21:15:58,990] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:15:59,002] {logging_mixin.py:109} INFO - [2023-04-28 21:15:59,001] {dag.py:2935} INFO - Setting next_dagrun for LocalIngestionDag to 2021-01-02 06:00:00+00:00
[2023-04-28 21:15:59,011] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.453 seconds
[2023-04-28 21:16:07,065] {processor.py:163} INFO - Started process (PID=245) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:16:07,065] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:16:07,066] {logging_mixin.py:109} INFO - [2023-04-28 21:16:07,066] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:16:07,435] {processor.py:690} INFO - Deactivated 1 DAGs which are no longer present in /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:16:07,435] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:16:08,392] {logging_mixin.py:109} INFO - [2023-04-28 21:16:08,392] {manager.py:496} INFO - Created Permission View: can edit on DAG:load_data_dag
[2023-04-28 21:16:08,397] {logging_mixin.py:109} INFO - [2023-04-28 21:16:08,397] {manager.py:496} INFO - Created Permission View: can read on DAG:load_data_dag
[2023-04-28 21:16:08,398] {logging_mixin.py:109} INFO - [2023-04-28 21:16:08,398] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:16:08,402] {logging_mixin.py:109} INFO - [2023-04-28 21:16:08,402] {dag.py:2415} INFO - Creating ORM DAG for load_data_dag
[2023-04-28 21:16:08,408] {logging_mixin.py:109} INFO - [2023-04-28 21:16:08,408] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2021-01-02 06:00:00+00:00
[2023-04-28 21:16:08,417] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 1.354 seconds
[2023-04-28 21:16:38,536] {processor.py:163} INFO - Started process (PID=279) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:16:38,537] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:16:38,538] {logging_mixin.py:109} INFO - [2023-04-28 21:16:38,538] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:16:38,890] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:16:38,895] {logging_mixin.py:109} INFO - [2023-04-28 21:16:38,895] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:16:38,905] {logging_mixin.py:109} INFO - [2023-04-28 21:16:38,905] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2021-01-02 06:00:00+00:00
[2023-04-28 21:16:38,912] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.377 seconds
[2023-04-28 21:17:09,031] {processor.py:163} INFO - Started process (PID=313) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:17:09,032] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:17:09,032] {logging_mixin.py:109} INFO - [2023-04-28 21:17:09,032] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:17:09,361] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:17:09,367] {logging_mixin.py:109} INFO - [2023-04-28 21:17:09,366] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:17:09,378] {logging_mixin.py:109} INFO - [2023-04-28 21:17:09,378] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2021-01-02 06:00:00+00:00
[2023-04-28 21:17:09,384] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.355 seconds
[2023-04-28 21:17:39,510] {processor.py:163} INFO - Started process (PID=781) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:17:39,511] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:17:39,511] {logging_mixin.py:109} INFO - [2023-04-28 21:17:39,511] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:17:39,852] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:17:39,859] {logging_mixin.py:109} INFO - [2023-04-28 21:17:39,859] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:17:39,871] {logging_mixin.py:109} INFO - [2023-04-28 21:17:39,871] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2022-02-02T06:00:00+00:00
[2023-04-28 21:17:39,879] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.371 seconds
[2023-04-28 21:18:09,995] {processor.py:163} INFO - Started process (PID=1249) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:18:09,996] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:18:09,996] {logging_mixin.py:109} INFO - [2023-04-28 21:18:09,996] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:18:10,349] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:18:10,355] {logging_mixin.py:109} INFO - [2023-04-28 21:18:10,354] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:18:10,366] {logging_mixin.py:109} INFO - [2023-04-28 21:18:10,366] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:18:10,373] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.380 seconds
[2023-04-28 21:18:40,479] {processor.py:163} INFO - Started process (PID=1283) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:18:40,479] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:18:40,480] {logging_mixin.py:109} INFO - [2023-04-28 21:18:40,480] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:18:40,808] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:18:40,813] {logging_mixin.py:109} INFO - [2023-04-28 21:18:40,813] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:18:40,824] {logging_mixin.py:109} INFO - [2023-04-28 21:18:40,823] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:18:40,830] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.353 seconds
[2023-04-28 21:19:10,942] {processor.py:163} INFO - Started process (PID=1317) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:19:10,942] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:19:10,943] {logging_mixin.py:109} INFO - [2023-04-28 21:19:10,943] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:19:11,308] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:19:11,316] {logging_mixin.py:109} INFO - [2023-04-28 21:19:11,315] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:19:11,326] {logging_mixin.py:109} INFO - [2023-04-28 21:19:11,326] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:19:11,334] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.395 seconds
[2023-04-28 21:19:41,454] {processor.py:163} INFO - Started process (PID=1351) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:19:41,455] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:19:41,455] {logging_mixin.py:109} INFO - [2023-04-28 21:19:41,455] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:19:41,872] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:19:41,880] {logging_mixin.py:109} INFO - [2023-04-28 21:19:41,880] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:19:41,890] {logging_mixin.py:109} INFO - [2023-04-28 21:19:41,890] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:19:41,898] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.446 seconds
[2023-04-28 21:20:12,015] {processor.py:163} INFO - Started process (PID=1385) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:20:12,016] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:20:12,016] {logging_mixin.py:109} INFO - [2023-04-28 21:20:12,016] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:20:12,406] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:20:12,412] {logging_mixin.py:109} INFO - [2023-04-28 21:20:12,411] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:20:12,424] {logging_mixin.py:109} INFO - [2023-04-28 21:20:12,423] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:20:12,431] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.418 seconds
[2023-04-28 21:20:20,452] {processor.py:163} INFO - Started process (PID=1402) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:20:20,453] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:20:20,454] {logging_mixin.py:109} INFO - [2023-04-28 21:20:20,454] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:20:20,887] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:20:20,892] {logging_mixin.py:109} INFO - [2023-04-28 21:20:20,892] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:20:20,903] {logging_mixin.py:109} INFO - [2023-04-28 21:20:20,903] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:20:20,912] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.462 seconds
[2023-04-28 21:21:31,576] {processor.py:163} INFO - Started process (PID=177) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:21:31,577] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:21:31,577] {logging_mixin.py:109} INFO - [2023-04-28 21:21:31,577] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:21:31,971] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:21:31,988] {logging_mixin.py:109} INFO - [2023-04-28 21:21:31,987] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:21:32,000] {logging_mixin.py:109} INFO - [2023-04-28 21:21:32,000] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:21:32,024] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.449 seconds
[2023-04-28 21:22:02,179] {processor.py:163} INFO - Started process (PID=211) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:22:02,180] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:22:02,180] {logging_mixin.py:109} INFO - [2023-04-28 21:22:02,180] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:22:02,579] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:22:02,586] {logging_mixin.py:109} INFO - [2023-04-28 21:22:02,586] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:22:02,598] {logging_mixin.py:109} INFO - [2023-04-28 21:22:02,598] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:22:02,607] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.430 seconds
[2023-04-28 21:22:32,740] {processor.py:163} INFO - Started process (PID=245) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:22:32,741] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:22:32,741] {logging_mixin.py:109} INFO - [2023-04-28 21:22:32,741] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:22:33,111] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:22:33,116] {logging_mixin.py:109} INFO - [2023-04-28 21:22:33,116] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:22:33,128] {logging_mixin.py:109} INFO - [2023-04-28 21:22:33,128] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:22:33,136] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.398 seconds
[2023-04-28 21:23:03,252] {processor.py:163} INFO - Started process (PID=279) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:23:03,253] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:23:03,253] {logging_mixin.py:109} INFO - [2023-04-28 21:23:03,253] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:23:03,593] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:23:03,598] {logging_mixin.py:109} INFO - [2023-04-28 21:23:03,598] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:23:03,610] {logging_mixin.py:109} INFO - [2023-04-28 21:23:03,610] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:23:03,618] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.367 seconds
[2023-04-28 21:23:33,770] {processor.py:163} INFO - Started process (PID=313) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:23:33,771] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:23:33,771] {logging_mixin.py:109} INFO - [2023-04-28 21:23:33,771] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:23:34,165] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:23:34,171] {logging_mixin.py:109} INFO - [2023-04-28 21:23:34,171] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:23:34,182] {logging_mixin.py:109} INFO - [2023-04-28 21:23:34,182] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:23:34,188] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.420 seconds
[2023-04-28 21:24:04,333] {processor.py:163} INFO - Started process (PID=347) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:24:04,334] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:24:04,334] {logging_mixin.py:109} INFO - [2023-04-28 21:24:04,334] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:24:04,664] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:24:04,669] {logging_mixin.py:109} INFO - [2023-04-28 21:24:04,669] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:24:04,679] {logging_mixin.py:109} INFO - [2023-04-28 21:24:04,679] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:24:04,685] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.354 seconds
[2023-04-28 21:24:34,822] {processor.py:163} INFO - Started process (PID=381) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:24:34,823] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:24:34,824] {logging_mixin.py:109} INFO - [2023-04-28 21:24:34,824] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:24:35,159] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:24:35,164] {logging_mixin.py:109} INFO - [2023-04-28 21:24:35,164] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:24:35,174] {logging_mixin.py:109} INFO - [2023-04-28 21:24:35,174] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:24:35,180] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.360 seconds
[2023-04-28 21:25:05,320] {processor.py:163} INFO - Started process (PID=415) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:25:05,321] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:25:05,321] {logging_mixin.py:109} INFO - [2023-04-28 21:25:05,321] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:25:05,656] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:25:05,662] {logging_mixin.py:109} INFO - [2023-04-28 21:25:05,661] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:25:05,671] {logging_mixin.py:109} INFO - [2023-04-28 21:25:05,671] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:25:05,678] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.360 seconds
[2023-04-28 21:25:35,814] {processor.py:163} INFO - Started process (PID=449) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:25:35,815] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:25:35,816] {logging_mixin.py:109} INFO - [2023-04-28 21:25:35,816] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:25:36,174] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:25:36,183] {logging_mixin.py:109} INFO - [2023-04-28 21:25:36,182] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:25:36,194] {logging_mixin.py:109} INFO - [2023-04-28 21:25:36,194] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:25:36,202] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.390 seconds
[2023-04-28 21:26:06,318] {processor.py:163} INFO - Started process (PID=483) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:26:06,319] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:26:06,319] {logging_mixin.py:109} INFO - [2023-04-28 21:26:06,319] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:26:06,679] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:26:06,685] {logging_mixin.py:109} INFO - [2023-04-28 21:26:06,685] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:26:06,695] {logging_mixin.py:109} INFO - [2023-04-28 21:26:06,695] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:26:06,701] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.385 seconds
[2023-04-28 21:26:36,870] {processor.py:163} INFO - Started process (PID=517) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:26:36,872] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:26:36,873] {logging_mixin.py:109} INFO - [2023-04-28 21:26:36,872] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:26:37,300] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:26:37,309] {logging_mixin.py:109} INFO - [2023-04-28 21:26:37,309] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:26:37,325] {logging_mixin.py:109} INFO - [2023-04-28 21:26:37,325] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:26:37,335] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.467 seconds
[2023-04-28 21:27:07,478] {processor.py:163} INFO - Started process (PID=582) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:27:07,479] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:27:07,479] {logging_mixin.py:109} INFO - [2023-04-28 21:27:07,479] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:27:07,819] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:27:07,826] {logging_mixin.py:109} INFO - [2023-04-28 21:27:07,825] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:27:07,835] {logging_mixin.py:109} INFO - [2023-04-28 21:27:07,835] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:27:07,842] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.366 seconds
[2023-04-28 21:27:37,982] {processor.py:163} INFO - Started process (PID=616) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:27:37,983] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:27:37,984] {logging_mixin.py:109} INFO - [2023-04-28 21:27:37,984] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:27:38,363] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:27:38,368] {logging_mixin.py:109} INFO - [2023-04-28 21:27:38,368] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:27:38,379] {logging_mixin.py:109} INFO - [2023-04-28 21:27:38,379] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:27:38,386] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.406 seconds
[2023-04-28 21:28:09,110] {processor.py:163} INFO - Started process (PID=650) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:28:09,111] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:28:09,111] {logging_mixin.py:109} INFO - [2023-04-28 21:28:09,111] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:28:09,443] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:28:09,448] {logging_mixin.py:109} INFO - [2023-04-28 21:28:09,448] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:28:09,457] {logging_mixin.py:109} INFO - [2023-04-28 21:28:09,457] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:28:09,464] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.355 seconds
[2023-04-28 21:28:29,782] {processor.py:163} INFO - Started process (PID=684) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:28:29,783] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:28:29,784] {logging_mixin.py:109} INFO - [2023-04-28 21:28:29,784] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:28:30,177] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:28:30,302] {logging_mixin.py:109} INFO - [2023-04-28 21:28:30,302] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:28:30,314] {logging_mixin.py:109} INFO - [2023-04-28 21:28:30,313] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:28:30,328] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.548 seconds
[2023-04-28 21:29:01,200] {processor.py:163} INFO - Started process (PID=177) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:29:01,201] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:29:01,202] {logging_mixin.py:109} INFO - [2023-04-28 21:29:01,202] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:29:01,590] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:29:01,596] {logging_mixin.py:109} INFO - [2023-04-28 21:29:01,596] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:29:01,608] {logging_mixin.py:109} INFO - [2023-04-28 21:29:01,608] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:29:01,616] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.417 seconds
[2023-04-28 21:29:31,754] {processor.py:163} INFO - Started process (PID=211) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:29:31,754] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:29:31,755] {logging_mixin.py:109} INFO - [2023-04-28 21:29:31,755] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:29:32,128] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:29:32,136] {logging_mixin.py:109} INFO - [2023-04-28 21:29:32,136] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:29:32,149] {logging_mixin.py:109} INFO - [2023-04-28 21:29:32,149] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:29:32,158] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.405 seconds
[2023-04-28 21:30:02,297] {processor.py:163} INFO - Started process (PID=245) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:30:02,298] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:30:02,298] {logging_mixin.py:109} INFO - [2023-04-28 21:30:02,298] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:30:02,655] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:30:02,661] {logging_mixin.py:109} INFO - [2023-04-28 21:30:02,661] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:30:02,675] {logging_mixin.py:109} INFO - [2023-04-28 21:30:02,675] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:30:02,685] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.389 seconds
[2023-04-28 21:30:32,807] {processor.py:163} INFO - Started process (PID=310) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:30:32,808] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:30:32,808] {logging_mixin.py:109} INFO - [2023-04-28 21:30:32,808] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:30:33,173] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:30:33,181] {logging_mixin.py:109} INFO - [2023-04-28 21:30:33,180] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:30:33,196] {logging_mixin.py:109} INFO - [2023-04-28 21:30:33,195] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:30:33,206] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.401 seconds
[2023-04-28 21:31:03,338] {processor.py:163} INFO - Started process (PID=344) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:31:03,338] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:31:03,339] {logging_mixin.py:109} INFO - [2023-04-28 21:31:03,339] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:31:03,690] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:31:03,696] {logging_mixin.py:109} INFO - [2023-04-28 21:31:03,696] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:31:03,708] {logging_mixin.py:109} INFO - [2023-04-28 21:31:03,708] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:31:03,715] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.379 seconds
[2023-04-28 21:31:33,855] {processor.py:163} INFO - Started process (PID=378) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:31:33,855] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:31:33,856] {logging_mixin.py:109} INFO - [2023-04-28 21:31:33,856] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:31:34,236] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:31:34,242] {logging_mixin.py:109} INFO - [2023-04-28 21:31:34,242] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:31:34,254] {logging_mixin.py:109} INFO - [2023-04-28 21:31:34,253] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:31:34,260] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.407 seconds
[2023-04-28 21:32:04,381] {processor.py:163} INFO - Started process (PID=412) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:32:04,381] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:32:04,382] {logging_mixin.py:109} INFO - [2023-04-28 21:32:04,382] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:32:04,713] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:32:04,719] {logging_mixin.py:109} INFO - [2023-04-28 21:32:04,719] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:32:04,730] {logging_mixin.py:109} INFO - [2023-04-28 21:32:04,730] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:32:04,738] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.359 seconds
[2023-04-28 21:32:34,856] {processor.py:163} INFO - Started process (PID=446) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:32:34,857] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:32:34,857] {logging_mixin.py:109} INFO - [2023-04-28 21:32:34,857] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:32:35,193] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:32:35,199] {logging_mixin.py:109} INFO - [2023-04-28 21:32:35,198] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:32:35,208] {logging_mixin.py:109} INFO - [2023-04-28 21:32:35,208] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:32:35,215] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.360 seconds
[2023-04-28 21:33:05,353] {processor.py:163} INFO - Started process (PID=480) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:33:05,354] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:33:05,355] {logging_mixin.py:109} INFO - [2023-04-28 21:33:05,355] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:33:05,718] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:33:05,725] {logging_mixin.py:109} INFO - [2023-04-28 21:33:05,725] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:33:05,736] {logging_mixin.py:109} INFO - [2023-04-28 21:33:05,736] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:33:05,743] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.392 seconds
[2023-04-28 21:33:27,469] {processor.py:163} INFO - Started process (PID=514) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:33:27,477] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:33:27,478] {logging_mixin.py:109} INFO - [2023-04-28 21:33:27,478] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:33:28,335] {logging_mixin.py:109} INFO - [2023-04-28 21:33:28,318] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 52, in <module>
    host=int(PG_HOST),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[2023-04-28 21:33:28,355] {processor.py:690} INFO - Deactivated 1 DAGs which are no longer present in /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:33:28,361] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:33:28,374] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.908 seconds
[2023-04-28 21:33:32,706] {processor.py:163} INFO - Started process (PID=531) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:33:32,709] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:33:32,711] {logging_mixin.py:109} INFO - [2023-04-28 21:33:32,710] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:33:33,485] {logging_mixin.py:109} INFO - [2023-04-28 21:33:33,478] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 53, in <module>
    port=int(PG_PORT),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[2023-04-28 21:33:33,506] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:33:33,525] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.822 seconds
[2023-04-28 21:34:07,920] {processor.py:163} INFO - Started process (PID=177) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:34:07,921] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:34:07,922] {logging_mixin.py:109} INFO - [2023-04-28 21:34:07,922] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:34:08,313] {logging_mixin.py:109} INFO - [2023-04-28 21:34:08,309] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 53, in <module>
    port=int(PG_PORT),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[2023-04-28 21:34:08,325] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:34:08,330] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.412 seconds
[2023-04-28 21:34:38,477] {processor.py:163} INFO - Started process (PID=211) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:34:38,477] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:34:38,478] {logging_mixin.py:109} INFO - [2023-04-28 21:34:38,478] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:34:38,862] {logging_mixin.py:109} INFO - [2023-04-28 21:34:38,859] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 53, in <module>
    port=int(PG_PORT),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[2023-04-28 21:34:38,881] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:34:38,887] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.412 seconds
[2023-04-28 21:35:09,053] {processor.py:163} INFO - Started process (PID=245) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:35:09,053] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:35:09,054] {logging_mixin.py:109} INFO - [2023-04-28 21:35:09,054] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:35:09,405] {logging_mixin.py:109} INFO - [2023-04-28 21:35:09,402] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 53, in <module>
    port=int(PG_PORT),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[2023-04-28 21:35:09,417] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:35:09,423] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.372 seconds
[2023-04-28 21:35:40,190] {processor.py:163} INFO - Started process (PID=279) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:35:40,191] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:35:40,192] {logging_mixin.py:109} INFO - [2023-04-28 21:35:40,192] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:35:40,577] {logging_mixin.py:109} INFO - [2023-04-28 21:35:40,574] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 53, in <module>
    port=int(PG_PORT),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[2023-04-28 21:35:40,588] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:35:40,595] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.406 seconds
[2023-04-28 21:36:10,746] {processor.py:163} INFO - Started process (PID=313) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:36:10,747] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:36:10,748] {logging_mixin.py:109} INFO - [2023-04-28 21:36:10,748] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:36:11,150] {logging_mixin.py:109} INFO - [2023-04-28 21:36:11,131] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 53, in <module>
    port=int(PG_PORT),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[2023-04-28 21:36:11,170] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:36:11,176] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.432 seconds
[2023-04-28 21:36:41,322] {processor.py:163} INFO - Started process (PID=347) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:36:41,323] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:36:41,324] {logging_mixin.py:109} INFO - [2023-04-28 21:36:41,324] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:36:41,664] {logging_mixin.py:109} INFO - [2023-04-28 21:36:41,661] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 53, in <module>
    port=int(PG_PORT),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[2023-04-28 21:36:41,674] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:36:41,680] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.359 seconds
[2023-04-28 21:37:11,802] {processor.py:163} INFO - Started process (PID=381) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:37:11,803] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:37:11,804] {logging_mixin.py:109} INFO - [2023-04-28 21:37:11,804] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:37:12,140] {logging_mixin.py:109} INFO - [2023-04-28 21:37:12,137] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 53, in <module>
    port=int(PG_PORT),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[2023-04-28 21:37:12,151] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:37:12,156] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.355 seconds
[2023-04-28 21:37:42,297] {processor.py:163} INFO - Started process (PID=415) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:37:42,298] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:37:42,299] {logging_mixin.py:109} INFO - [2023-04-28 21:37:42,299] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:37:42,637] {logging_mixin.py:109} INFO - [2023-04-28 21:37:42,634] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 53, in <module>
    port=int(PG_PORT),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[2023-04-28 21:37:42,647] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:37:42,653] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.357 seconds
[2023-04-28 21:38:12,806] {processor.py:163} INFO - Started process (PID=449) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:38:12,807] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:38:12,807] {logging_mixin.py:109} INFO - [2023-04-28 21:38:12,807] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:38:13,161] {logging_mixin.py:109} INFO - [2023-04-28 21:38:13,158] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 53, in <module>
    port=int(PG_PORT),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[2023-04-28 21:38:13,171] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:38:13,177] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.373 seconds
[2023-04-28 21:38:43,298] {processor.py:163} INFO - Started process (PID=483) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:38:43,299] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:38:43,299] {logging_mixin.py:109} INFO - [2023-04-28 21:38:43,299] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:38:43,682] {logging_mixin.py:109} INFO - [2023-04-28 21:38:43,679] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 53, in <module>
    port=int(PG_PORT),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[2023-04-28 21:38:43,693] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:38:43,699] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.402 seconds
[2023-04-28 21:38:52,756] {processor.py:163} INFO - Started process (PID=517) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:38:52,757] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:38:52,758] {logging_mixin.py:109} INFO - [2023-04-28 21:38:52,758] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:38:53,148] {logging_mixin.py:109} INFO - None
[2023-04-28 21:38:53,153] {logging_mixin.py:109} INFO - [2023-04-28 21:38:53,149] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 54, in <module>
    port=int(PG_PORT),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[2023-04-28 21:38:53,163] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:38:53,170] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.416 seconds
[2023-04-28 21:39:07,032] {processor.py:163} INFO - Started process (PID=534) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:39:07,032] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:39:07,033] {logging_mixin.py:109} INFO - [2023-04-28 21:39:07,033] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:39:07,428] {logging_mixin.py:109} INFO - PG_PORT: None
[2023-04-28 21:39:07,432] {logging_mixin.py:109} INFO - [2023-04-28 21:39:07,429] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_dag.py", line 54, in <module>
    port=int(PG_PORT),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[2023-04-28 21:39:07,443] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:39:07,448] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.418 seconds
[2023-04-28 21:41:14,328] {processor.py:163} INFO - Started process (PID=177) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:41:14,329] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:41:14,330] {logging_mixin.py:109} INFO - [2023-04-28 21:41:14,330] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:41:14,873] {logging_mixin.py:109} INFO - PG_PORT: None
[2023-04-28 21:41:14,900] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:41:14,915] {logging_mixin.py:109} INFO - [2023-04-28 21:41:14,915] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:41:14,932] {logging_mixin.py:109} INFO - [2023-04-28 21:41:14,932] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:41:14,953] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.627 seconds
[2023-04-28 21:41:45,106] {processor.py:163} INFO - Started process (PID=242) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:41:45,107] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:41:45,107] {logging_mixin.py:109} INFO - [2023-04-28 21:41:45,107] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:41:45,483] {logging_mixin.py:109} INFO - PG_PORT: None
[2023-04-28 21:41:45,496] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:41:45,503] {logging_mixin.py:109} INFO - [2023-04-28 21:41:45,502] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:41:45,514] {logging_mixin.py:109} INFO - [2023-04-28 21:41:45,514] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:41:45,522] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.418 seconds
[2023-04-28 21:42:15,661] {processor.py:163} INFO - Started process (PID=276) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:42:15,662] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:42:15,662] {logging_mixin.py:109} INFO - [2023-04-28 21:42:15,662] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:42:15,998] {logging_mixin.py:109} INFO - PG_PORT: None
[2023-04-28 21:42:16,011] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:42:16,018] {logging_mixin.py:109} INFO - [2023-04-28 21:42:16,018] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:42:16,028] {logging_mixin.py:109} INFO - [2023-04-28 21:42:16,028] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:42:16,037] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.377 seconds
[2023-04-28 21:42:46,176] {processor.py:163} INFO - Started process (PID=310) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:42:46,177] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:42:46,177] {logging_mixin.py:109} INFO - [2023-04-28 21:42:46,177] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:42:46,507] {logging_mixin.py:109} INFO - PG_PORT: None
[2023-04-28 21:42:46,520] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:42:46,525] {logging_mixin.py:109} INFO - [2023-04-28 21:42:46,525] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:42:46,536] {logging_mixin.py:109} INFO - [2023-04-28 21:42:46,535] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:42:46,542] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.368 seconds
[2023-04-28 21:43:16,681] {processor.py:163} INFO - Started process (PID=344) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:43:16,682] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:43:16,682] {logging_mixin.py:109} INFO - [2023-04-28 21:43:16,682] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:43:17,020] {logging_mixin.py:109} INFO - PG_PORT: None
[2023-04-28 21:43:17,033] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:43:17,040] {logging_mixin.py:109} INFO - [2023-04-28 21:43:17,039] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:43:17,050] {logging_mixin.py:109} INFO - [2023-04-28 21:43:17,050] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:43:17,058] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.379 seconds
[2023-04-28 21:43:47,202] {processor.py:163} INFO - Started process (PID=378) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:43:47,203] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:43:47,203] {logging_mixin.py:109} INFO - [2023-04-28 21:43:47,203] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:43:47,563] {logging_mixin.py:109} INFO - PG_PORT: None
[2023-04-28 21:43:47,578] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:43:47,585] {logging_mixin.py:109} INFO - [2023-04-28 21:43:47,584] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:43:47,596] {logging_mixin.py:109} INFO - [2023-04-28 21:43:47,596] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:43:47,604] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.404 seconds
[2023-04-28 21:44:17,746] {processor.py:163} INFO - Started process (PID=412) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:44:17,747] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:44:17,747] {logging_mixin.py:109} INFO - [2023-04-28 21:44:17,747] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:44:18,103] {logging_mixin.py:109} INFO - PG_PORT: None
[2023-04-28 21:44:18,117] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:44:18,124] {logging_mixin.py:109} INFO - [2023-04-28 21:44:18,124] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:44:18,136] {logging_mixin.py:109} INFO - [2023-04-28 21:44:18,136] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:44:18,143] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.399 seconds
[2023-04-28 21:44:48,886] {processor.py:163} INFO - Started process (PID=446) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:44:48,887] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:44:48,888] {logging_mixin.py:109} INFO - [2023-04-28 21:44:48,888] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:44:49,255] {logging_mixin.py:109} INFO - PG_PORT: None
[2023-04-28 21:44:49,271] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:44:49,279] {logging_mixin.py:109} INFO - [2023-04-28 21:44:49,279] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:44:49,295] {logging_mixin.py:109} INFO - [2023-04-28 21:44:49,294] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:44:49,304] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.421 seconds
[2023-04-28 21:45:19,451] {processor.py:163} INFO - Started process (PID=480) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:45:19,452] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:45:19,453] {logging_mixin.py:109} INFO - [2023-04-28 21:45:19,453] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:45:19,781] {logging_mixin.py:109} INFO - PG_PORT: None
[2023-04-28 21:45:19,818] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:45:19,825] {logging_mixin.py:109} INFO - [2023-04-28 21:45:19,825] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:45:19,835] {logging_mixin.py:109} INFO - [2023-04-28 21:45:19,835] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:45:19,842] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.392 seconds
[2023-04-28 21:45:49,991] {processor.py:163} INFO - Started process (PID=514) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:45:49,992] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:45:49,993] {logging_mixin.py:109} INFO - [2023-04-28 21:45:49,993] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:45:50,330] {logging_mixin.py:109} INFO - PG_PORT: None
[2023-04-28 21:45:50,343] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:45:50,348] {logging_mixin.py:109} INFO - [2023-04-28 21:45:50,348] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:45:50,359] {logging_mixin.py:109} INFO - [2023-04-28 21:45:50,358] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:45:50,365] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.378 seconds
[2023-04-28 21:46:20,546] {processor.py:163} INFO - Started process (PID=548) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:46:20,547] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:46:20,547] {logging_mixin.py:109} INFO - [2023-04-28 21:46:20,547] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:46:20,878] {logging_mixin.py:109} INFO - PG_PORT: None
[2023-04-28 21:46:20,890] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:46:20,895] {logging_mixin.py:109} INFO - [2023-04-28 21:46:20,895] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:46:20,905] {logging_mixin.py:109} INFO - [2023-04-28 21:46:20,905] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:46:20,912] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.368 seconds
[2023-04-28 21:46:51,037] {processor.py:163} INFO - Started process (PID=582) to work on /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:46:51,038] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_data_dag.py for tasks to queue
[2023-04-28 21:46:51,039] {logging_mixin.py:109} INFO - [2023-04-28 21:46:51,039] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:46:51,402] {logging_mixin.py:109} INFO - PG_PORT: None
[2023-04-28 21:46:51,416] {processor.py:654} INFO - DAG(s) dict_keys(['load_data_dag']) retrieved from /opt/airflow/dags/load_data_dag.py
[2023-04-28 21:46:51,422] {logging_mixin.py:109} INFO - [2023-04-28 21:46:51,422] {dag.py:2396} INFO - Sync 1 DAGs
[2023-04-28 21:46:51,434] {logging_mixin.py:109} INFO - [2023-04-28 21:46:51,434] {dag.py:2935} INFO - Setting next_dagrun for load_data_dag to 2023-04-02T06:00:00+00:00
[2023-04-28 21:46:51,442] {processor.py:171} INFO - Processing /opt/airflow/dags/load_data_dag.py took 0.407 seconds
