[0m01:48:34.958036 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2f15fb7010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2f14d84490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2f14d849d0>]}


============================== 01:48:34.963259 | 1197a8cc-e1e7-4064-939d-cf6b9f50248f ==============================
[0m01:48:34.963259 [info ] [MainThread]: Running with dbt=1.5.0
[0m01:48:34.964661 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m01:49:08.184523 [debug] [MainThread]: Starter project path: /usr/local/lib/python3.11/site-packages/dbt/include/starter_project
[0m01:52:46.429919 [info ] [MainThread]: Profile taxi_data written to /root/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m01:52:46.431248 [info ] [MainThread]: 
Your new dbt project "taxi_data" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m01:52:46.432512 [debug] [MainThread]: Command `dbt init` succeeded at 01:52:46.432399 after 251.49 seconds
[0m01:52:46.433364 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2f14d86550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2f162ff550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2f1841e490>]}
[0m01:52:46.434222 [debug] [MainThread]: Flushing usage events
[0m02:18:25.885788 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fee63459610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fee64a7ff50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fee634599d0>]}


============================== 02:18:25.891580 | b8922251-6f57-4345-88dc-d923e5adace2 ==============================
[0m02:18:25.891580 [info ] [MainThread]: Running with dbt=1.5.0
[0m02:18:25.892849 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m02:18:28.641124 [error] [MainThread]: Encountered an error:

[0m02:18:28.649388 [error] [MainThread]: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/dbt/cli/requires.py", line 86, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbt/cli/requires.py", line 71, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbt/cli/main.py", line 459, in init
    results = task.run()
              ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbt/task/init.py", line 286, in run
    project_name = self.get_valid_project_name()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbt/task/init.py", line 243, in get_valid_project_name
    name = click.prompt("Enter a name for your project (letters, digits, underscore)")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/termui.py", line 166, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/termui.py", line 149, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m02:18:28.650975 [debug] [MainThread]: Command `dbt init` failed at 02:18:28.650867 after 2.78 seconds
[0m02:18:28.651975 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fee63482510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fee64a7ff50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fee66b16250>]}
[0m02:18:28.652873 [debug] [MainThread]: Flushing usage events
